packages:
  - package
  - example

overrides:
  '@eslint/eslintrc>ajv': ^6
  '@eslint/js': '>=10.0.0'
  '@stylistic/eslint-plugin': '>=5.0.0'
  ajv@<8.18.0: '>=8.18.0'
  diff@<8.0.3: '>=8.0.3'
  eslint: '>=10.0.0'
  eslint>ajv: ^6
  markdown-it: '>=14.1.1'
  minimatch@<10.2.1: '>=10.2.1'

publishBranch: main
