packages:
  - package
  - example

allowBuilds:
  esbuild: false
  unrs-resolver: false

blockExoticSubdeps: true

minimumReleaseAge: 10080 # 7 days in minutes

minimumReleaseAgeExclude:
  - pnpm@11.5.3

overrides:
  semver: '>=7'

publishBranch: main

strictPeerDependencies: false

trustPolicy: no-downgrade
