packages:
  - package
  - example

allowBuilds:
  esbuild: false
  unrs-resolver: false

blockExoticSubdeps: true

minimumReleaseAge: 10080 # 7 days in minutes

minimumReleaseAgeExclude:
  - ip-address@10.1.1

overrides:
  ip-address@<=10.1.0: ^10.1.1
  semver: '>=7'

publishBranch: main

strictPeerDependencies: false

trustPolicy: no-downgrade
