name: Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

  workflow_dispatch: null
env:
  OIDC_IAM_ROLE_ARN: ${{ secrets.OIDC_IAM_ROLE_ARN }}
  AWS_REGION: us-west-2

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      name: Install pnpm
      with:
        run_install: |
          - recursive: true

    - name: Build
      run: pnpm build

    - name: Lint
      run: pnpm run --if-present --recursive --parallel lint

  deploy-example:
    # 同時実行すると CREATE_IN_PROGRESS や UPDATE_IN_PROGRESS 状態で cdk deploy を行う可能性があるため抑止する
    concurrency:
      group: "cloudformation-aws-lambda-mcp-server-example"
      cancel-in-progress: false

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Install pnpm
      uses: pnpm/setup@c9883cc79df532ad1a7b81bf9ab944ceb090d65c # v2.0.0

    - name: Install global dependenceis
      run: pnpm add -g esbuild

    - name: Build
      run: pnpm build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
      with:
        role-to-assume: ${{ env.OIDC_IAM_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: ${{ env.AWS_REGION }}

    - name: deploy
      working-directory: ./example
      run: |
        pnpm dlx aws-cdk@latest deploy --require-approval=never
